name: Combined Tender Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Tender Scraper
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        python tender_scraper.py

    - name: Commit updated JSON files
      if: success()
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add data/*.json || true
        git commit -m "Update tender JSON files" || echo "No changes"
        git push || echo "Nothing to push"
